Create handler for the new email
nhsengland/innovation-service-backend-api pull request #442
Opened 2024-08-29 18:38 UTC by pedrocarloto

2024-08-30 10:12 UTC, manuelsousa-bjss requested changes

2024-08-30 10:12 UTC, manuelsousa-bjss commented on apps/notifications/_handlers/admin/new-announcement.handler.ts
> +        announcement_url: `[${announcement.params?.link?.label}](${announcement.params?.link?.url})`
I think you need to test if the params has a link and add this if it has or '' if it doesn't otherwise it will output strange things to the template.

2024-08-30 10:12 UTC, manuelsousa-bjss commented on apps/notifications/_handlers/admin/new-announcement.handler.ts
> +          announcement_url: `[${announcement.params?.link?.label}](${announcement.params?.link?.url})`
Same as other

2024-09-02 16:07 UTC, diogo-costa-bjss approved these changes

2024-09-02 16:17 UTC, merged